version: "3.4"
services:
  ldap-master:
    image: ubisecure-ldap:${UBISECURE_LDAP_VERSION}
    entrypoint:
     - /usr/sbin/slapd
     - -f
     - /etc/openldap/slapd.conf
     - -d
     - "256"
    ports:
      - target: 389
        published: 389
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          - node.platform.os==linux
          - node.labels.ubisecure-ldap==master
    environment:
     - role=master
    volumes:
     - "/data/ubisecure-ldap-master:/var/lib/openldap"
    labels:
     - app=ubisecure
     - tier=backend
    configs:
     - source: ldap-master-slapd.conf
       target: /etc/openldap/slapd.conf
     - source: ldap-base.conf
       target: /etc/openldap/base.conf
    networks:
      backend:
        aliases:
          - ldap-master
  ldap-slave:
    image: ubisecure-ldap:${UBISECURE_LDAP_VERSION}
    entrypoint:
     - /usr/sbin/slapd
     - -f
     - /etc/openldap/slapd.conf
     - -d
     - "256"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          - node.platform.os==linux
          - node.labels.ubisecure-ldap==slave
    environment:
     - role=slave
    volumes:
     - "/data/ubisecure-ldap-slave:/var/lib/openldap"
    labels:
     - app=ubisecure
     - tier=backend
    configs:
     - source: ldap-slave-slapd.conf
       target: /etc/openldap/slapd.conf
     - source: ldap-base.conf
       target: /etc/openldap/base.conf
    networks:
      backend:
        aliases:
          - ldap-slave
    ports:
      - target: 389
        published: 389
        protocol: tcp
        mode: host
  sso:
    image: ubisecure-sso:${UBISECURE_SSO_VERSION}
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role==worker
          - node.platform.os==linux
    secrets:
     - source: sso-unix.config
       target: /usr/local/ubisecure/ubilogin-sso/ubilogin/unix.config
    labels:
     - app=ubisecure
     - tier=frontend
    networks:
     - frontend
     - backend
  syslog:
    image: balabit/syslog-ng:3.14.1
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          - node.platform.os==linux
          - node.labels.ubisecure-syslog==true
    volumes:
     - "/data/ubisecure-syslog:/logs"
    labels:
     - app=ubisecure
     - tier=backend
    configs:
     - source: syslog-ng.conf
       target: /etc/syslog-ng/syslog-ng.conf
    networks:
      backend:
        aliases:
          - syslog
configs:
  syslog-ng.conf:
    file: ./ubisecure-syslog/syslog-ng.conf
  ldap-master-slapd.conf:
    file: ./ubisecure-ldap/ldap-master-slapd.conf
  ldap-slave-slapd.conf:
    file: ./ubisecure-ldap/ldap-slave-slapd.conf
  ldap-base.conf:
    file: ./ubisecure-ldap/ldap-base.conf
secrets:
  sso-unix.config:
    file: ./ubisecure-sso/unix.config
networks:
    frontend:
        driver: overlay
    backend:
        driver: overlay